#include "../common/evk.glsl"

#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable
#extension GL_EXT_shader_16bit_storage : enable
#extension GL_EXT_buffer_reference : enable

layout(buffer_reference) readonly buffer ReadBufferFp16 { float16_t x[]; };
PUSH(
    ReadBufferFp16 inputTensor;
    RID outputImage;
    uint width;
    uint height;
    uint paddedWidth;
    uint inputChannels;
)

COMPUTE(256, 1, 1)
void main() {
    uint pixel = gl_GlobalInvocationID.x;
    uint pixelCount = width * height;
    if (pixel >= pixelCount) return;

    uint x = pixel % width;
    uint y = pixel / width;
    uint inputIndex = (y * paddedWidth + x) * inputChannels;
    vec3 value = clamp(vec3(inputTensor.x[inputIndex + 0u],
                            inputTensor.x[inputIndex + 1u],
                            inputTensor.x[inputIndex + 2u]),
                       vec3(0.0), vec3(1.0));
    imageStore(Image2DW[outputImage], ivec2(x, y), vec4(value, 1.0));
}
