#include "../common/evk.glsl"

#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable
#extension GL_EXT_shader_16bit_storage : enable
#extension GL_EXT_buffer_reference : enable

layout(buffer_reference) readonly buffer ReadBufferFp16 { float16_t x[]; };
layout(buffer_reference) writeonly buffer WriteBufferFp16 { float16_t x[]; };
PUSH(
    ReadBufferFp16 inputTensor;
    WriteBufferFp16 outputTensor;
    uint outputWidth;
    uint outputHeight;
    uint channels;
)

COMPUTE(256, 1, 1)
void main() {
    uint index = gl_GlobalInvocationID.x;
    uint elementCount = outputWidth * outputHeight * channels;
    if (index >= elementCount) return;
    uint channel = index % channels;
    uint pixel = index / channels;
    uint outputX = pixel % outputWidth;
    uint outputY = pixel / outputWidth;
    uint inputWidth = outputWidth * 2u;
    uint inputBase = ((outputY * 2u) * inputWidth + outputX * 2u) * channels + channel;
    float16_t value = max(inputTensor.x[inputBase], inputTensor.x[inputBase + channels]);
    inputBase += inputWidth * channels;
    value = max(value, inputTensor.x[inputBase]);
    value = max(value, inputTensor.x[inputBase + channels]);
    outputTensor.x[index] = value;
}
