#include "evk.frag"

#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable
#extension GL_EXT_shader_16bit_storage : enable
#extension GL_EXT_buffer_reference : enable

layout(buffer_reference) readonly buffer ReadBufferFp16 { float16_t x[]; };
layout(buffer_reference) writeonly buffer WriteBufferFp32 { float x[]; };
PUSH(
    ReadBufferFp16 inputTensor;
    WriteBufferFp32 outputTensor;
    uint width;
    uint height;
    uint paddedWidth;
    uint inputChannels;
)

COMPUTE(256, 1, 1)
void main() {
    uint index = gl_GlobalInvocationID.x;
    uint elementCount = width * height * 3u;
    if (index >= elementCount) return;
    uint channel = index % 3u;
    uint pixel = index / 3u;
    uint x = pixel % width;
    uint y = pixel / width;
    uint inputIndex = (y * paddedWidth + x) * inputChannels + channel;
    outputTensor.x[index] = clamp(float(inputTensor.x[inputIndex]), 0.0, 1.0);
}
