#include "../common/evk.glsl"

#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable
#extension GL_EXT_shader_16bit_storage : enable
#extension GL_EXT_buffer_reference : enable

layout(buffer_reference) readonly buffer ReadBufferFp16 { float16_t x[]; };
layout(buffer_reference) buffer WriteBufferFp16 { float16_t x[]; };

PUSH(
    ReadBufferFp16 inputBuffer;
    WriteBufferFp16 outputBuffer;
    uint batches;
    uint channels;
    uint inputHeight;
    uint inputWidth;
    uint scale;
)

COMPUTE(8, 8, 1)
void main() {
    uint ox = gl_GlobalInvocationID.x;
    uint oy = gl_GlobalInvocationID.y;
    uint plane = gl_GlobalInvocationID.z;
    uint outputHeight = inputHeight * scale;
    uint outputWidth = inputWidth * scale;
    if (ox >= outputWidth || oy >= outputHeight || plane >= batches * channels) return;

    uint n = plane / channels;
    uint c = plane % channels;
    uint iy = oy / scale;
    uint ix = ox / scale;
    uint inputIndex = ((n * channels + c) * inputHeight + iy) * inputWidth + ix;
    uint outputIndex = ((n * channels + c) * outputHeight + oy) * outputWidth + ox;
    outputBuffer.x[outputIndex] = inputBuffer.x[inputIndex];
}
